#        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

name: Update manifest.js

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Building manifest.js
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: node .scripts/manifest.js
    - name: Commit files
      run: |
        git config --local user.name "github-actions[bot]"
        git commit -m "skipci: Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
