name: Update manifest.json

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Building manifest.json
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: node .scripts/manifest.js
    - name: Commit files
      run: |
        git commit -m "skipci: Updated manifest.json" -a || exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
